#Atividade 1
crie um array unidimensional comos números de 1 a 12. transforme este array
em uma matriz de 3 linhas e 4 colunas.

(DESAFIO: Aplique a transposição da matriz para criar as dimensões em 4x3 (.transpose) e, 
em seguida, crie um array unidimencional (.flatten)).

In [7]:
import numpy as np

# array unidimensional
array_unidimensional = np.arange(1, 13)

# matriz de 3 linhas e 4 colunas
matriz = array_unidimensional.reshape(3, 4)

# Transposição da matriz
matriz_transposta = matriz.T

# Criação de um array unidimensional a partir da matriz transposta
array_final = matriz_transposta.flatten()

# Resultados
print("Array Unidimensional:")
print(array_unidimensional)
print("\nMatriz 3x4:")
print(matriz)
print("\nMatriz Transposta 4x3:")
print(matriz_transposta)
print("\nArray Unidimensional a partir da matriz transposta:")
print(array_final)


Array Unidimensional:
[ 1  2  3  4  5  6  7  8  9 10 11 12]

Matriz 3x4:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Matriz Transposta 4x3:
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]

Array Unidimensional a partir da matriz transposta:
[ 1  5  9  2  6 10  3  7 11  4  8 12]


Atividade 2 (GITHUB):
Leia o arquivo ClassicDisco.csv  trabalho em aulas anteriores e aplique o comando .describe()
para gerar uma análise estatística prévia dos dados. Não esqueça dos comandos para verificar as primeiras e últimas linhas do dataset omo apoio nessa  atividade.

In [ ]:
##EXEMPLO DE LEITURA:
dados=pd.read_csv('bloco-sob-contrato')
print(dados.head())