Conversões entre Arrays e Series:

In [4]:
import pandas as pd
import numpy as np

In [5]:
#convertendo um array pra uma série:
arr1=np.array([10,20,30])
serie1=pd.Series(arr1)
print(arr1)
print(serie1)

[10 20 30]
0    10
1    20
2    30
dtype: int64


In [6]:
#convertendo uma série pra um array:
arr2=serie1.to_numpy()
print(arr2)

[10 20 30]


Dataframes e suas Principais Funções:

In [7]:
#criação:
arr3=np.array([[1,2],[3,4]])
df_arr=pd.DataFrame(arr3, columns=['A','B'])
print(arr3)
print(df_arr)

[[1 2]
 [3 4]]
   A  B
0  1  2
1  3  4


In [8]:
#transformando uma coluna em uma série:
coluna_serie=df_arr['A']
print(coluna_serie)

0    1
1    3
Name: A, dtype: int64


In [9]:
#contagem de valores:
estados=pd.DataFrame({'Cidade':['RJ','SP','MG','ES','RJ','RJ','SP']})
print(estados['Cidade'].value_counts())

Cidade
RJ    3
SP    2
MG    1
ES    1
Name: count, dtype: int64


In [10]:
#Cálculos Estatísticos:
notas=pd.DataFrame({'Notas':[2,4,6,8,10,12,12,12,14]})
print(notas['Notas'].sum()) #soma
print(notas['Notas'].mean()) #média
print(notas['Notas'].median()) #mediana
print(notas.describe()) #resumo das estatísticas

80
8.88888888888889
10.0
           Notas
count   9.000000
mean    8.888889
std     4.136558
min     2.000000
25%     6.000000
50%    10.000000
75%    12.000000
max    14.000000


In [ ]:
##EXEMPLO DE LEITURA:
dados=pd.read_csv('blocos-sob-contrato-jan.csv')
print(dados.head())
estatistica=dados.describe()
print(estatistica)