***Importação das Bibliotecas:

In [1]:
import pandas as pd
import numpy as np

Criação de um Array a partir de uma lista:

In [2]:
lista1=[1,2,3,4,5,6]
array1=np.array(lista1)
print(array1)

[1 2 3 4 5 6]


Principais Funções para Definição de Arrays partindo do Zero:

In [3]:
print(array1.dtype)

int64


In [4]:
print(array1.shape)

(6,)


In [5]:
zeros=np.zeros((4,3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [6]:
number_one=np.ones((4,3))
print(number_one)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [7]:
vazio=np.empty((4,4))
print(vazio)

[[6.95166047e-310 6.95166047e-310 6.95166047e-310 1.69119330e-306]
 [1.78022342e-306 1.05700345e-307 8.45568130e-307 1.69117157e-306]
 [6.23059726e-307 8.90100844e-307 8.34445562e-308 7.56601165e-307]
 [7.56591659e-307 2.22523004e-307 1.78020440e-306 8.01089062e-307]]


In [8]:
sequencia=np.arange(-100,-10,10)
print(sequencia)

[-100  -90  -80  -70  -60  -50  -40  -30  -20]


In [9]:
aleatorio=np.random.rand(2,3)
print(aleatorio)

[[0.19564207 0.82725655 0.1834793 ]
 [0.4736723  0.41864289 0.62380254]]


In [10]:
array2=array1.reshape((3,2))
print(array2)

[[1 2]
 [3 4]
 [5 6]]


In [11]:
quebra=np.split(array2,3)
print(quebra)

[array([[1, 2]]), array([[3, 4]]), array([[5, 6]])]


In [12]:
array3=np.array([1,2])
array4=np.array([3,4])
print(array3,array4)
uniao=np.concatenate((array3,array4))
print(uniao)

[1 2] [3 4]
[1 2 3 4]


Operações com Séries Pandas:

Criação:

In [13]:
serie1=pd.Series([10,20,30],index=['a','b','c'])
print(serie1)

a    10
b    20
c    30
dtype: int64


Seleção por Índice:

In [14]:
print(serie1['a'])
print('--------')
print(serie1[['a']])
print('--------')
print(serie1[['a','c']])

10
--------
a    10
dtype: int64
--------
a    10
c    30
dtype: int64


Operações de Filtragem e Aritméticas:

In [15]:
filtro1=serie1[serie1>15]
print(filtro1)
print('--------')
serie2=serie1*3
print(serie2)

b    20
c    30
dtype: int64
--------
a    30
b    60
c    90
dtype: int64


In [16]:
serie3=pd.Series([1,2,3,4])
serie4=pd.Series([5,6,7,8])

#Operações Fundamentais:
print(serie3+serie4)
print('--------')
print(serie3-serie4)
print('--------')
print(serie3*serie4)
print('--------')
print(serie3/serie4)

0     6
1     8
2    10
3    12
dtype: int64
--------
0   -4
1   -4
2   -4
3   -4
dtype: int64
--------
0     5
1    12
2    21
3    32
dtype: int64
--------
0    0.200000
1    0.333333
2    0.428571
3    0.500000
dtype: float64


In [17]:
#Suporte a Valores Nulos:

serievazia=pd.Series([10,np.nan,30])
print(serievazia) #NaN = 'Null as Number'

0    10.0
1     NaN
2    30.0
dtype: float64


In [18]:
print(serie3+serievazia)
print('--------')
print(serie3-serievazia)
print('--------')
print(serie3*serievazia)
print('--------')
print(serie3/serievazia)

0    11.0
1     NaN
2    33.0
3     NaN
dtype: float64
--------
0    -9.0
1     NaN
2   -27.0
3     NaN
dtype: float64
--------
0    10.0
1     NaN
2    90.0
3     NaN
dtype: float64
--------
0    0.1
1    NaN
2    0.1
3    NaN
dtype: float64
